const CART_KEY="barril_diablo_cart_v1";
let cart=JSON.parse(localStorage.getItem(CART_KEY)||"{}");
const grid=document.getElementById("productGrid"),search=document.getElementById("search"),category=document.getElementById("category"),cartModal=document.getElementById("cartModal");
function toast(m){const e=document.getElementById("toast");e.textContent=m;e.classList.add("show");setTimeout(()=>e.classList.remove("show"),1800)}
function saveCart(){localStorage.setItem(CART_KEY,JSON.stringify(cart));updateCount()}
function updateCount(){const t=Object.values(cart).reduce((s,i)=>s+i.cantidad,0);document.getElementById("cartCount").textContent=t;document.getElementById("floatingCount").textContent=t}
function loadCategories(){[...new Set(PRODUCTOS.map(p=>p.categoria))].sort().forEach(c=>{const o=document.createElement("option");o.value=c;o.textContent=c;category.appendChild(o)})}
function renderProducts(){const q=search.value.trim().toLowerCase(),cat=category.value;const f=PRODUCTOS.filter(p=>(!cat||p.categoria===cat)&&(!q||p.nombre.toLowerCase().includes(q)||p.codigo.includes(q)));grid.innerHTML=f.map(p=>`<article class="product"><span class="badge">${p.categoria}</span><div><h3>${p.nombre}</h3><small>${p.unidad}</small></div><button class="add" data-code="${p.codigo}">Agregar al carrito</button></article>`).join("")||'<p class="empty">No se encontraron productos.</p>';grid.querySelectorAll(".add").forEach(b=>b.addEventListener("click",()=>{const p=PRODUCTOS.find(x=>x.codigo===b.dataset.code);if(!cart[p.codigo])cart[p.codigo]={...p,cantidad:0};cart[p.codigo].cantidad++;saveCart();toast("Producto agregado")}))}
function changeQty(c,d){if(!cart[c])return;cart[c].cantidad+=d;if(cart[c].cantidad<=0)delete cart[c];saveCart();renderCart()}
function renderCart(){const items=Object.values(cart),box=document.getElementById("cartItems");if(!items.length){box.innerHTML='<p class="empty">Tu carrito está vacío.</p>';return}box.innerHTML=items.map(i=>`<div class="cart-row"><div><strong>${i.nombre}</strong><br><small>${i.unidad}</small></div><div class="qty"><button data-a="minus" data-c="${i.codigo}">−</button><b>${i.cantidad}</b><button data-a="plus" data-c="${i.codigo}">+</button><button class="remove" data-a="remove" data-c="${i.codigo}">×</button></div></div>`).join("");box.querySelectorAll("button").forEach(b=>b.addEventListener("click",()=>{if(b.dataset.a==="plus")changeQty(b.dataset.c,1);if(b.dataset.a==="minus")changeQty(b.dataset.c,-1);if(b.dataset.a==="remove"){delete cart[b.dataset.c];saveCart();renderCart()}}))}
function openCart(){renderCart();cartModal.showModal()}
function sendWhatsapp(){const items=Object.values(cart);if(!items.length){toast("Agrega productos primero");return}const entrega=document.querySelector('input[name="entrega"]:checked').value,notes=document.getElementById("notes").value.trim();const lines=items.map((i,n)=>`${n+1}. ${i.cantidad} x ${i.nombre}`);let msg=`Hola, El Barril del Diablo.\n\nDeseo realizar el siguiente pedido:\n\n${lines.join("\n")}\n\nModalidad: ${entrega}`;if(notes)msg+=`\nIndicaciones: ${notes}`;msg+="\n\nPor favor, confirmen disponibilidad y el total del pedido.";window.open(`https://wa.me/51942180159?text=${encodeURIComponent(msg)}`,"_blank")}
search.addEventListener("input",renderProducts);category.addEventListener("change",renderProducts);document.getElementById("openCart").addEventListener("click",openCart);document.getElementById("floatingCart").addEventListener("click",openCart);document.getElementById("closeCart").addEventListener("click",()=>cartModal.close());document.getElementById("clearCart").addEventListener("click",()=>{cart={};saveCart();renderCart()});document.getElementById("sendWhatsapp").addEventListener("click",sendWhatsapp);
loadCategories();renderProducts();updateCount();
